---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: three-tier-app
spec:
  clusterIP: None #Headless
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: three-tier-app
spec:
  serviceName: "mongo-svc"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:6
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: persistentvolumeformongo
          mountPath: /data/db
        
      volumes:
        - name: persistentvolumeformongo
          persistentVolumeClaim:
            claimName: mongodb-pvc


