apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: three-tier-app
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: public.ecr.aws/f9w4b6z1/mern-stack-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
