name: 'CI/CD For 3-Tier MERN Stack App'

on: 
   push:
      branches: [main]
   workflow_dispatch:

env:
  region: 'ap-south-1'

jobs:
  ContiniousIntegration:
    runs-on: ubuntu-22.04

    steps:

      - name: 'Checkout Repo For Github-Hosted Runner'
        uses: actions/checkout@v4


      - name: 'Login To AWS'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.region }}


      - name: Generate Authentication Token
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/f9w4b6z1

      - name: 'Login to Docker Hub (Required for Docker Scout)'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_API_TOKEN }}


      - name: 'Build Frontend Image'
        run: | 

          docker build -t mern-stack-frontend frontend

      - name: 'Docker Scout Scan: Frontend'
        uses: docker/scout-action@v1
        with:
          command: cves
          image: mern-stack-frontend:latest
          ignore-base: true # Ignores base OS vulnerabilities but scans our code
          only-severities: critical,high #Severity type
          exit-code: true # Fails the pipeline if critical/high vulnerabilities are found
          

      - name: 'Tag And Push Secure Frontend Image'
        run: |

          docker tag mern-stack-frontend:latest public.ecr.aws/f9w4b6z1/mern-stack-frontend:latest

          docker push public.ecr.aws/f9w4b6z1/mern-stack-frontend:latest

          echo "Frontend Image Build & Pushed Successfully"
          sleep 2


      - name: 'Build Backend Image'
        run: |
          
          docker build -t mern-stack-backend backend

        
      - name: 'Docker Scout Scan: Backend'
        uses: docker/scout-action@v1
        with:
          command: cves
          image: mern-stack-backend:latest
          ignore-base: true 
          only-severities: critical,high 
          exit-code: true 
      
      
      - name: 'Tag And Push Secure Backend Image'
        run: | 

          docker tag mern-stack-backend:latest public.ecr.aws/f9w4b6z1/mern-stack-backend:latest

          docker push public.ecr.aws/f9w4b6z1/mern-stack-backend:latest

          echo "Backend Image Build & Pushed Successfully"
          sleep 2


      - name: 'Remove Images From The Runner'
        run: |
          docker rmi -f public.ecr.aws/f9w4b6z1/mern-stack-frontend:latest

          docker rmi -f public.ecr.aws/f9w4b6z1/mern-stack-backend:latest

      

  ContiniousDeployment:
    runs-on: self-hosted
    needs: ContiniousIntegration

    steps:

      - name: 'Checkout Repo For Self-Hosted Runner'
        uses: actions/checkout@v4


      - name: 'Login To AWS'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.region }}


      - name: 'AWS ECR Login'  # Translates AWS credentials into Docker authentication
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin public.ecr.aws/f9w4b6z1


      - name: 'Pull Frontend, Backend & MongoDB From ECR'
        run: |
          docker pull public.ecr.aws/f9w4b6z1/mern-stack-frontend:latest
          docker pull public.ecr.aws/f9w4b6z1/mern-stack-backend:latest
          docker pull mongo:6

        #Keep persistent volume ready as it is not a part of CI/CD pipeline, Its an infrastructure resource.

      - name: 'Creating A Namespace'
        run: |
          kubectl apply -f namespace.yaml
          kubectl config set-context --current --namespace=three-tier-app



      - name: 'Creating A PersistentVolumeClaim & Deploying The Database'
        run: |
          kubectl apply -f persistent-volume-claim.yaml
          kubectl apply -f mongodb-statefulset.yaml

      - name: 'Wait for Database To Be Ready'  
        run: |
          kubectl rollout status statefulset/mongodb -n three-tier-app --timeout=300s
  

      - name: 'Deploying The Frontend'
        run: |
          kubectl apply -f frontend/frontend-deployment.yaml
          kubectl apply -f frontend/frontend-service.yaml 
          kubectl rollout restart deployment/frontend-deployment -n three-tier-app



      - name: 'Deploying The Backend'
        run: |
          kubectl apply -f backend/backend-deployment.yaml
          kubectl apply -f backend/backend-service.yaml
          kubectl rollout restart deployment/backend-deployment -n three-tier-app
      
